-- Word Corners — D1 (SQLite) schema.
-- Apply with:
--   npx wrangler d1 execute word-corners --local  --file=db/schema.sql
--   npx wrangler d1 execute word-corners --remote --file=db/schema.sql
--
-- One row per completed game. Everything here is a summary the client
-- computes during play and posts once, at game over (see functions/api/games.js).

CREATE TABLE IF NOT EXISTS games (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  -- Anonymous per-device id generated by the client and kept in
  -- localStorage. Not an account: clearing site data makes a new "player".
  player_id      TEXT    NOT NULL,
  -- Reserved for a future initials/nickname entry on the game-over screen.
  player_name    TEXT,
  -- GAME_VERSION from public/js/version.js at the time the game was played.
  game_version   TEXT    NOT NULL,
  score          INTEGER NOT NULL,
  -- Wall-clock milliseconds from the first letter being dealt to game over.
  duration_ms    INTEGER NOT NULL,
  -- Valid words scored. words_3..words_6_plus partition this count by length.
  words_total    INTEGER NOT NULL,
  words_3        INTEGER NOT NULL,
  words_4        INTEGER NOT NULL,
  words_5        INTEGER NOT NULL,
  words_6_plus   INTEGER NOT NULL,
  -- Blank/wildcard tiles awarded over the course of the game.
  blanks_earned  INTEGER NOT NULL,
  created_at     TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- Global leaderboard reads: "highest score, any player".
CREATE INDEX IF NOT EXISTS idx_games_score ON games (score DESC);

-- Personal-best reads: "highest score for this device".
CREATE INDEX IF NOT EXISTS idx_games_player_score ON games (player_id, score DESC);
